# Generated by Django 3.0 on 2019-12-19 16:55

from django.db import migrations, models
import django.db.models.deletion
import hashtag_monitor.apps.monitor.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='quoted_tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.Tweet'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, validators=[hashtag_monitor.apps.monitor.models.validate_is_hashtag, hashtag_monitor.apps.monitor.models.validate_nb_hashtag], verbose_name='Hashtag name'),
        ),
    ]
