# Generated by Django 3.0 on 2019-12-19 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20191219_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='quoted_tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_tweet_fk', to='monitor.Tweet'),
        ),
    ]
