# Generated by Django 3.0 on 2019-12-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20191219_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='retweeted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tweet_retweeted', to='monitor.Tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='quoted_tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tweet_quoted', to='monitor.Tweet'),
        ),
    ]
