# Generated by Django 3.0 on 2019-12-19 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20191219_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='hashtag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Hashtag'),
        ),
    ]
