# Generated by Django 3.0 on 2019-12-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_auto_20191219_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
