# Generated by Django 3.0 on 2019-12-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_remove_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='url',
            field=models.CharField(max_length=100, null=True, verbose_name='Link to tweet'),
        ),
    ]
