# Generated by Django 3.0 on 2019-12-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_auto_20191223_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='screen_name',
            field=models.CharField(default='', max_length=100, verbose_name='Username'),
        ),
    ]
