# Generated by Django 3.0 on 2019-12-23 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0017_auto_20191223_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='filter_level',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Twitter filter level'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='quoted_tweet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweet_quoted', to='monitor.Tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweeted',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweet_retweeted', to='monitor.Tweet'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Link to tweet'),
        ),
    ]
