# Generated by Django 3.0 on 2019-12-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0019_auto_20191226_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='screen_name',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Username'),
        ),
    ]
